### ISSUE TITLE
cannot find MainActivity

### ISSUE THREAD

**Issue by yidan621** [multunus/moveit-mobile#2]
Trying to install the Android app on a connected Android 4.4 device. Got this error:

Starting: Intent { cmp=com.multunus.moveit/.MainActivity }
Error type 3
Error: Activity class {com.multunus.moveit/com.multunus.moveit.MainActivity} does not exist.

I did not change the application Id or package name. 
Any idea??

**Comment by akshaysmurthy** [comment]
@yidan621 Please give us a day to look into this.

**Comment by peterlazar1993** [comment]
@yidan621 We have some code here https://github.com/multunus/moveit-mobile/blob/master/android/app/build.gradle#L135-L145. It basically appends one of "dev" or "staging" to the package name. This is done so that both versions of the app can be installed on the same device.

**Comment by yidan621** [comment]
Thanks for the quick reply! 
It works now! I tried running it from Android Studio instead of the command line. 
But when I tried registering, a Toast popped up saying, 'Sorry, we cannot connect to the server"
I have changed the appServerRootURL to my IP address with port 8081. Am I missing anything for the setup?

**Comment by peterlazar1993** [comment]
@yidan621 There is an accompanying server with the app. We are not maintaining this app anymore and hence there are lots of issues with the current repo. If you could tell me why you are interested in this repo, I could point you to better maintained RN repos.

**Comment by yidan621** [comment]
@peterlazar1993  Thanks Peter！I'm a RN newbie trying to learn from open sourced RN projects.  Your app sounds really cool 👍 👍  If you could point me to some repos, that would be really great!

**Comment by peterlazar1993** [comment]
@yidan621 That's awesome. I'd highly recommend the f8 app from facebook http://makeitopen.com/

Also find a list of open source apps here:
https://github.com/jondot/awesome-react-native/blob/master/README.md#open-source-apps

**Comment by yidan621** [comment]
Thanks :)
